### ISSUE TITLE
Implement a robot loader for three types of robots (Franka, Kuka, UR)

### ISSUE THREAD

**Issue by karimsiala** [openroboticmetaverse/mvp-webapp#26]
<h2>✨ Desired Solution </h2>
Develop a frontend component to load three types of robots (Franka, Kuka, UR5e) into the simulation environment.

<h2>📚 Technical Details </h2>
- Use the `urdfloader` library which was previously used in the TDSI demo.
- Store the URDF files for each robot locally until we transition to storing them in the database.

<h2>🚧 Challenges and Roadblocks </h2>
- Ensuring compatibility and seamless loading of URDF files for Franka, Kuka, and UR5e.
- Handling different configurations and settings for each robot type.

<h2>💡 Examples and References </h2>

[Universal_Robots_ROS2_Description](https://github.com/UniversalRobots/Universal_Robots_ROS2_Description)

[kuka_robot_descriptions](https://github.com/kroshu/kuka_robot_descriptions)

<h2>🔗 Subtasks  </h2>

- [ ] Design the structure of the loader component.
- [ ] Implement the loader functionality for Franka.
- [ ] Implement the loader functionality for Kuka.
- [ ] Implement the loader functionality for UR5e.
- [ ] Test the loader with all three robot types in the simulation environment.

**Comment by med-ayssar** [comment]
@karimsiala, what is special about those three models?

**Comment by karimsiala** [comment]
> @karimsiala, what is special about those three models?

Since we already got these 3 models  running in the MuJoCo simulation, we figured it would be easier to start with and load them in the Frontend for now.

You can check them in the simulation in the tutorial branch of  `mvp_mujoco_simulation`
https://github.com/openroboticmetaverse/mvp_mujoco_simulation/tree/tutorial

But you can safely ignore this issues if you are working on #25, that would be the better approach in the long run.
