### ISSUE TITLE
 Implement communication between frontend and backend using FastAPI

### ISSUE THREAD

**Issue by karimsiala** [openroboticmetaverse/mvp-webapp#28]
<h2>✨ Desired Solution </h2>
Develop a backend using FastAPI to handle API requests from the frontend, process the requests, and send responses back to the frontend.

<h2>📚 Technical Details </h2>
- Use FastAPI to create the backend server.
- Define API endpoints for communication with the frontend.

<h2>💡 Examples and References </h2>

- Reference [FastAPI documentation](https://fastapi.tiangolo.com/)
- Look at existing examples of FastAPI integration with frontend frameworks.

<h2>🔗 Subtasks  </h2>

- [x] Set up the FastAPI server.
- [x] Define API endpoints for communication with the frontend.
- [x] Implement request handling and response sending in the backend.

**Comment by sandys9995** [comment]
@karimsiala  I think we can add more subtasks here now.

**Comment by karimsiala** [comment]
Checkout #27, it contains tasks related to starting/stopping simulation and transmitting its data

**Comment by karimsiala** [comment]
Since we now have the basic backend setup I'll close this issue and we continue on #27. We'll get back to creating concrete APIs in the future
